<a href="https://colab.research.google.com/github/RenanTzy/exercicios-Python/blob/main/Ol%C3%A1%2C_este_%C3%A9_o_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Definição de matrix

In [17]:
from numpy import matrix

#estrutura de uma matrix.
matriz_A = matrix([
            [1,2,3], #A virgula server para indicar que houve a quebra de minha da matriz
            [4,5,6],
            [7,8,9]
            ])

print("Matriz A")
print(matriz_A)
print("Dimensão da matriz A\n",matriz_A.shape) #função shape indica o tamanho da matriz. EX: 3x3

Matriz A
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensão da matriz A
 (3, 3)


Tipos especiais de matrix

In [16]:
from numpy import zeros, ones, identity

#Gera uma matriz B, que é composta por zeros, do tamanho 4x3 do tipo inteiro.
matriz_B = zeros((4,3), dtype = 'int')
print("Matriz zeros:")
print(matriz_B, "\n")

#Gera uma matriz C, que é composta pelo número 1, onde a mesma será do 2x3 do tipo decimal(ponto flutuante).
matriz_C = ones((2,3), dtype = 'float')
print("Matriz uns:")
print(matriz_C, "\n")

#Gereção de uma matriz identidade de tamanho 4x4, onde sua diagonal será composta por 1 e os demais lugares serão 0.
matriz_D = identity(4)
print("Matriz Identidade:")
print(matriz_D, "\n")

#cada termo da matriz ones será miltiplicado por 6, podem ser efetuadas outras operações.
matriz_E = 6 * ones((2,3), dtype = 'int')
print(matriz_E)


Matriz zeros:
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]] 

Matriz uns:
[[1. 1. 1.]
 [1. 1. 1.]] 

Matriz Identidade:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[6 6 6]
 [6 6 6]]


Operações com matriz

In [25]:
"""
Matriz transposta, as linhas viram colunas e
as colunas viram linhas
"""

from numpy import matrix, transpose

matrix_A = matrix([
                  [1,4,2],
                  [4,2,9]
                  ])

print("Matriz A")
print(matrix_A)

print("\nMatriz transposta da matriz A")
matrix_A_T = transpose(matrix_A)
print(matrix_A_T)

"""
Matriz inversa
"""
from numpy import matrix, linalg

matrix_B = matrix([
                  [7,2,4],
                  [3,5,9],
                  [1,6,9]
                  ])

print("Matrix B")
print(matrix_B)

matrix_B_I = linalg.inv(matrix_B)
print("\nMatrix inversa de B")
print(matrix_B_I)

Matriz A
[[1 4 2]
 [4 2 9]]

Matriz transposta da matriz A
[[1 4]
 [4 2]
 [2 9]]
Matrix B
[[7 2 4]
 [3 5 9]
 [1 6 9]]

Matrix inversa de B
[[ 0.19148936 -0.12765957  0.04255319]
 [ 0.38297872 -1.25531915  1.08510638]
 [-0.27659574  0.85106383 -0.61702128]]


In [31]:
"""
Maior e menor elemento
"""
from numpy import matrix

matriz_a = matrix([
                  [7,3,4],
                  [4,6,9]
                  ])

#função max e min retorman o menor e maior valor na matriz.
#axis for igual a 0 verifica o valores entres as colunas, caso seja igual a 1 será nas linhas
maior_valor_A = matriz_a.max()
menor_valor_A = matriz_a.min()

print(maior_valor_A)
print(menor_valor_A)

"""
Soma dos elementos

"""

#Funcão de soma entre os termos da matriz, tanto no eixo x, y e toda a matriz.
soma_coluna = matriz_a.sum(axis=0)
soma_linhas = matriz_a.sum(axis=1)
soma_total = matriz_a.sum()

print("\n"soma_coluna)
print("\n",soma_linhas)
print("\n",soma_total)

9
3
[[11  9 13]]

 [[14]
 [19]]

 33
